title: blog
description: > # this means to ignore newlines until "baseurl:"
  Personal blog for Daniel Tapia Martinez. 
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Daniel Tapia Martínez # add your name
author-img:  T.jpg # add your photo
about-author:  Tamart # add description
social-twitter:  itsTamart # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: itsTamart # add your Github handle
social-linkedin: tamart # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: dtamart # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
